---

- name: "Prepare management cluster file {{ cluster_config }}"
  ansible.builtin.template:
    src: templates/management_cluster.yml.j2
    dest: "{{ cluster_config }}"
    mode: "0644"

- name: Create management cluster
  block:
    - name: Deploy management cluster
      changed_when: true
      ansible.builtin.shell: |
        tanzu mc create --file {{ cluster_config }} --verbose 6 --log-file {{ cluster_log }}

    - name: Export management cluster kubeconfig
      changed_when: true
      ansible.builtin.shell: |
        tanzu mc kubeconfig get --export-file {{ kubeconfig_management }} --admin

  environment:
    TKG_CUSTOM_IMAGE_REPOSITORY: "{{ tkg_custom_image_repository }}"
    TKG_CUSTOM_IMAGE_REPOSITORY_CA_CERTIFICATE: "{{ tkg_custom_image_repository_ca_certificate | b64encode }}"
    TKG_HTTP_PROXY_ENABLED: "{{ tkg_http_proxy_enabled | string | lower }}"
    TKG_HTTP_PROXY: "{{ tkg_http_proxy_computed }}"
    TKG_HTTPS_PROXY: "{{ tkg_https_proxy_computed }}"
    TKG_NO_PROXY: "{{ tkg_no_proxy_computed }}"
    TKG_PROXY_CA_CERT: "{{ tkg_proxy_ca_cert_b64 }}"

